# Generated by Django 4.2.7 on 2025-08-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bid",
            name="unique_bid_per_auction_player_team_amount",
        ),
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together={("auction", "player", "team", "amount")},
        ),
    ]
